{{- if .Values.nexus.encryption.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nexus.fullname" . }}-encryption
  namespace: {{ default .Release.Namespace .Values.namespaces.nexusNs.name | quote }}
  labels:
{{ include "nexus.labels" . | nindent 4 }}
  {{- if .Values.nexus.extraLabels }}
    {{- with .Values.nexus.extraLabels }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
    app.kubernetes.io/component: nexus
type: Opaque
stringData:
  encryption.json: |
    {
      "active": "{{ .Values.nexus.encryption.active }}",
      "keys": [
        {{- $n := len $.Values.nexus.encryption.keys }}
        {{- range $id, $_ := .Values.nexus.encryption.keys }}
        {{- $n = sub $n 1 }}
        {
          "id": "{{ $id }}",
          "key": "{{ .key }}"
        }
        {{- if gt $n 0 }},{{ end }}
        {{- end }}
      ]
    }
{{- end }}
